#!/bin/bash

SHELL_DIR=$(which $0)
SHELL_DIR=$(readlink -f $SHELL_DIR)
SHELL_DIR=$(dirname $SHELL_DIR)

NAME=""
if [ -f CMakeLists.txt ] ; then
    NAME=$(cat CMakeLists.txt | grep project | head -1 | sed 's/project(\([^ ]*\).*/\1/')
    DOCKERFILE="${SHELL_DIR}/cpp.Dockerfile"
    IMAGE="ide-shell-cpp"
else
    DOCKERFILE="${SHELL_DIR}/cpp.Dockerfile"
    IMAGE="ide-shell"
fi

if [ -z "$NAME" ] ; then
    NAME=$(pwd | sed 's|.*/\([^/]*\)$|\1|')
fi

docker build --tag $IMAGE "${SHELL_DIR}" -f "${DOCKERFILE}" > /dev/null 2>&1
NAME=$(echo "$NAME-$RANDOM" | tr -cd 'a-z0-9-_')

if [ ! -d .ide-shell-home ] ; then
    mkdir .ide-shell-home
fi

DOCKER_GID=$(stat -c '%g' /var/run/docker.sock)

ADDITIONAL_ARGS=""
if [ "$NETWORK" == "host" ] ; then
    ADDITIONAL_ARGS="--network host"
    echo "Using host network mode!"
    sleep 1
fi

exec docker run -it \
    --name "${NAME}" \
    -e "CONTAINER_NAME=$NAME" \
    -e "HOME=$HOME" \
    -e "CARGO_HOME=$HOME/.cargo" \
    -v "/var/run/docker.sock:/var/run/docker.sock" \
    -v "$(pwd)/.ide-shell-home:$HOME:rw" \
    -v "${SHELL_DIR}/bashrc:$HOME/.bashrc:ro" \
    -v "$(pwd):$(pwd)" \
    -v "$HOME/.claude/:$HOME/.claude/" \
    -v "${SHELL_DIR}/managed-settings.json:/etc/claude-code/managed-settings.json:ro" \
    -v "$HOME/.claude.json:$HOME/.claude.json" \
    --workdir "$(pwd)" \
    --user "$(id -u):$(id -g)" \
    --group-add "${DOCKER_GID}" \
    $ADDITIONAL_ARGS \
    "$IMAGE" \
    /bin/bash
